server:
  port: 8003


#应用名称
spring:
  application:
    name: dcloud-link

#服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 101.42.236.154:8848
        username: nacos
        password: nacos

  # 数据源 ds0 第一个数据库
  shardingsphere:
    datasource:
      #数据源名称
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://127.0.0.1:3306/dcloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: Aa18760120328
      names: ds0

    props:
      # 打印执行的数据库以及语句
      sql:
        show: true

#配置plus打印sql日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

